version: '3.8'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - "80:8080"
    volumes:
      - /data/docker/filebrowser/:/database/database.db
      - /data/docker/filebrowser/:/.filebrowser.json
      - /data/docker/filebrowser/data/:/data
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
volumes:
  portainer_data:

