version: "3.6"
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    ports:
      - "8080:80"
    volumes:
      - ${USERDIR}/docker/filebrowser/filebrowser.db:/database/database.db
      - ${USERDIR}/docker/filebrowser/filebrowser.json:/.filebrowser.json
    restart: always

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
